[aliases]
	start = init 
	pl = pull
	psh = push
	example_name = config --global user.name "example_name"
	mail = config --global user.mail "example.mail@gmail.com"
	br = branch
	fusion = merge
	message = commit -m 
    	all = add -A
    	history = log 
    	check = status
    	specific = status -s
    	undo = revert
    	copyTo = clone
	graph = log -- oneline --graph
	toRemote = remote add origin
	pshForced = push origin HEAD --force
	command = help -a
