Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.network "private_network", type: "dhcp"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
    end
  
    config.vm.provision "shell", inline: <<-SHELL
      # Install Nix
      sh <(curl -L https://nixos.org/nix/install) --daemon
    SHELL
end